import logging

from fastapi import APIRouter, Depends
from fastapi.responses import JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.controllers.deps import get_current_user_id, require_admin, CurrentUser
from app.schemas.baseline import (
    BaselineCreateRequest,
    DiffGenerateRequest,
    BaselineDTO,
    DiffReportDTO,
    DiffReportSummaryDTO,
)
from app.schemas.common import ApiResponse, PageResponse
from app.services.baseline_service import BaselineService

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/baselines", tags=["Baseline"])


@router.get("", response_model=ApiResponse[PageResponse[BaselineDTO]])
async def list_baselines(
    page: int = 1,
    page_size: int = 20,
    user_id: int = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    service = BaselineService(db)
    result = await service.list_baselines(page, page_size)
    return ApiResponse(data=result)


@router.post("", response_model=ApiResponse[BaselineDTO])
async def create_baseline(
    req: BaselineCreateRequest,
    user_id: int = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    service = BaselineService(db)
    result = await service.create_baseline(req, user_id)
    logger.info("Baseline created by user %d: %s", user_id, req.name)
    return ApiResponse(data=result)


@router.get("/{baseline_id}", response_model=ApiResponse[BaselineDTO])
async def get_baseline(
    baseline_id: int,
    user_id: int = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    service = BaselineService(db)
    result = await service.get_baseline(baseline_id)
    return ApiResponse(data=result)


@router.delete("/{baseline_id}", response_model=ApiResponse)
async def delete_baseline(
    baseline_id: int,
    admin: CurrentUser = Depends(require_admin),
    db: AsyncSession = Depends(get_db),
):
    service = BaselineService(db)
    deleted = await service.delete_baseline(baseline_id)
    if not deleted:
        return ApiResponse(code=404, message="Baseline not found")
    logger.info("Baseline deleted by admin %s: id=%d", admin.username, baseline_id)
    return ApiResponse(message="Deleted successfully")


@router.get("/{baseline_id}/diffs", response_model=ApiResponse[list[DiffReportSummaryDTO]])
async def list_diffs(
    baseline_id: int,
    user_id: int = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    service = BaselineService(db)
    result = await service.list_diffs(baseline_id)
    return ApiResponse(data=result)


@router.post("/{baseline_id}/diffs", response_model=ApiResponse[DiffReportDTO])
async def generate_diff(
    baseline_id: int,
    req: DiffGenerateRequest,
    user_id: int = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    service = BaselineService(db)
    result = await service.generate_diff(baseline_id, req, user_id)
    logger.info("Diff generated by user %d: baseline=%d task=%d", user_id, baseline_id, req.task_id)
    return ApiResponse(data=result)


@router.get("/diffs/{diff_id}", response_model=ApiResponse[DiffReportDTO])
async def get_diff(
    diff_id: int,
    user_id: int = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    service = BaselineService(db)
    result = await service.get_diff(diff_id)
    return ApiResponse(data=result)


@router.get("/diffs/{diff_id}/report")
async def get_diff_report(
    diff_id: int,
    user_id: int = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Return the raw diff JSON payload (categorized by file/language/algorithm/risk)."""
    service = BaselineService(db)
    result = await service.get_diff(diff_id)
    return JSONResponse(content=result.diff)
